servers: '10.0.1.256,10.0.2.256'
installs:
  swapspace: yes
  nginx: yes
  php:
    install: yes
    composer: yes
    version: 8.3
  node_and_npm: yes
  redis: yes
  database:
    postgres: yes
    mysql: no
    db_username: postgres
    db_password: secret
  certbot: yes
  memcache: no
  beanstalk: no